### ISSUE TITLE
1.1 Research: Compatible light strips with Arduino Nano

### ISSUE THREAD

**Issue by danialhbma** [danialhbma/MINDS-Baking#3]

**Comment by Elakkiya2405** [comment]
https://randomnerdtutorials.com/guide-for-ws2812b-addressable-rgb-led-strip-with-arduino/

**Comment by Elakkiya2405** [comment]
https://learn.adafruit.com/rgb-led-strips/usage

**Comment by Elakkiya2405** [comment]
https://howtomechatronics.com/tutorials/arduino/how-to-control-ws2812b-individually-addressable-leds-using-arduino/
